var ed_domiciliaria_hospitalaria = {
	"type": "FeatureCollection",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },                                                                               
	"features": [
		{ "type": "Feature", "properties": { "fna": "ESCUELA HOSPITALARIA Y DOMICILIARIA - DR. ATILIO REBELLO", "fun": "Activo", "cueanexo": "260006900", "amg": "Urbano", "ges": "Estatal", "codJurid": "302", "Región": "VI", "Localidad": "COMODORO RIVADAVIA", "Dependenci": "Provincial", "Oferta": "Inicial; Primaria; Secundaria", "Nivel": "Domiciliaria - Hospitalaria", "Modalidad": "Común", "cod_area": "297", "telefono": "4550297", "email": "ehyd302@gmail.com", "sitioweb": null, "responsabl": "Carolina Del Carmen Vargas", "resp_tel": "0297-4888845", "resp_email": "caro76vargas@hotmail.com", "departamen": "ESCALANTE", "calle": "RAMÓN LISTA", "num_calle": "2150", "cod_postal": "U9005" }, "geometry": { "type": "Point", "coordinates": [ -67.4623224, -45.8331249 ] } },
		{ "type": "Feature", "properties": { "fna": "ESCUELA HOSPITALARIA Y DOMICILIARIA Nº 303", "fun": "Activo", "cueanexo": "260010300", "amg": "Urbano", "ges": "Estatal", "codJurid": "303", "Región": "IV", "Localidad": "TRELEW", "Dependenci": "Provincial", "Oferta": "Inicial; Primaria; Secundaria; Especial Primaria", "Nivel": "Domiciliaria - Hospitalaria", "Modalidad": "Común; Especial", "cod_area": "280", "telefono": "4428987", "email": "esc303hdom@yahoo.com.ar", "sitioweb": null, "responsabl": "Silvia Rosana Dlugapolski", "resp_tel": "280-154374193", "resp_email": "swiming2201@yahoo.com.ar", "departamen": "RAWSON", "calle": "AVDA. COLOMBIA", "num_calle": "NULL", "cod_postal": "U9100" }, "geometry": { "type": "Point", "coordinates": [ -65.3128, -43.2486 ] } },
		{ "type": "Feature", "properties": { "fna": "ESCUELA HOSPITALARIA Y DOMICILIARIA Nº 304", "fun": "Activo", "cueanexo": "260018100", "amg": "Urbano", "ges": "Estatal", "codJurid": "304", "Región": "III", "Localidad": "ESQUEL", "Dependenci": "Provincial", "Oferta": "Inicial; Primaria; Secundaria; Especial Primaria; Adultos Primaria", "Nivel": "Domiciliaria - Hospitalaria", "Modalidad": "Común; Especial; Adultos", "cod_area": "2945", "telefono": "453428", "email": "escuela_304@yahoo.com.ar", "sitioweb": null, "responsabl": "Ruth Rebeca Wodtcke", "resp_tel": "02945-15558199", "resp_email": "ruthwodtcke@hotmail.com", "departamen": "FUTALEUFÚ", "calle": "25 DE MAYO", "num_calle": "150", "cod_postal": "U9200" }, "geometry": { "type": "Point", "coordinates": [ -71.3159926, -42.9178156 ] } },
		{ "type": "Feature", "properties": { "fna": "ESCUELA HOSPITALARIA Y DOMICILIARIA - DR. ANDRÉS ISOLA", "fun": "Activo", "cueanexo": "260020300", "amg": "Urbano", "ges": "Estatal", "codJurid": "305", "Región": "II", "Localidad": "PUERTO MADRYN", "Dependenci": "Provincial", "Oferta": "Inicial; Primaria; Secundaria; Especial Primaria - Secundaria", "Nivel": "Domiciliaria - Hospitalaria", "Modalidad": "Común; Especial", "cod_area": "280", "telefono": "4453238 4455792", "email": "escuela305@gmail.com", "sitioweb": null, "responsabl": "Laura Élida Susana Guttig", "resp_tel": "280-4540800", "resp_email": "guttiglaura@gmail.com", "departamen": "BIEDMA", "calle": "ROBERTO GÓMEZ", "num_calle": "383", "cod_postal": "U9120" }, "geometry": { "type": "Point", "coordinates": [ -65.0417291, -42.759113 ] } },
		{ "type": "Feature", "properties": { "fna": "ESCUELA HOSPITALARIA Y DOMICILIARIA - DR. RICARDO GUTIÉRREZ", "fun": "Activo", "cueanexo": "260024400", "amg": "Urbano", "ges": "Estatal", "codJurid": "301", "Región": "VI", "Localidad": "COMODORO RIVADAVIA", "Dependenci": "Provincial", "Oferta": "Inicial; Primaria; Secundaria", "Nivel": "Domiciliaria - Hospitalaria", "Modalidad": "Común", "cod_area": "297", "telefono": "4482339", "email": "eschosp301@hotmail.com", "sitioweb": null, "responsabl": "Marian Perez Barrias", "resp_tel": "2975092888", "resp_email": "marian75@hotmail.com", "departamen": "ESCALANTE", "calle": "JUANA DE AZURDUY", "num_calle": "1369", "cod_postal": "U9000" }, "geometry": { "type": "Point", "coordinates": [ -67.5440058, -45.8605897 ] } },
		{ "type": "Feature", "properties": { "fna": "ESCUELA HOSPITALARIA Y DOMICILIARIA Nº 306", "fun": "Activo", "cueanexo": "260045000", "amg": "Urbano", "ges": "Estatal", "codJurid": "306", "Región": "IV", "Localidad": "RAWSON", "Dependenci": "Provincial", "Oferta": "Inicial; Primaria; Secundaria; Especial Primaria - Secundaria; Adultos Primaria - Secundaria", "Nivel": "Domiciliaria - Hospitalaria", "Modalidad": "Común; Especial; Adultos", "cod_area": "280", "telefono": "4484553", "email": "escuela306@yahoo.com.ar", "sitioweb": "www.chubut.edu.ar instituciones 306", "responsabl": "Gladys Estela Montecinos", "resp_tel": "0280-154362824  4485892", "resp_email": "gladysmonte33@yahoo.com.ar", "departamen": "RAWSON", "calle": "AVDA. TENIENTE CORONEL JULIÁN MURGA", "num_calle": "NULL", "cod_postal": "U9103" }, "geometry": { "type": "Point", "coordinates": [ -65.0938, -43.2965 ] } },
		{ "type": "Feature", "properties": { "fna": "ESCUELA HOSPITALARIA Y DOMICILIARIA Nº 307", "fun": "Activo", "cueanexo": "260049600", "amg": "Urbano", "ges": "Estatal", "codJurid": "307", "Región": "V", "Localidad": "SARMIENTO", "Dependenci": "Provincial", "Oferta": "Inicial; Primaria; Secundaria; Especial Inicial - Primaria; Adultos Primaria - Secundaria", "Nivel": "Domiciliaria - Hospitalaria", "Modalidad": "Común; Especial; Adultos", "cod_area": "297", "telefono": "4898351", "email": "sin informacion", "sitioweb": null, "responsabl": "Maria Esther Jaramillo", "resp_tel": "0297-154189410", "resp_email": "mmaritajaramillo@hotmail.com", "departamen": "SARMIENTO", "calle": "FONTANA", "num_calle": "555", "cod_postal": "U9020" }, "geometry": { "type": "Point", "coordinates": [ -69.0722766, -45.5926524 ] } },
		{ "type": "Feature", "properties": { "fna": "ESCUELA DOMICILIARIA Y HOSPITALARIA Nº 308", "fun": "Activo", "cueanexo": "260077500", "amg": "Urbano", "ges": "Estatal", "codJurid": "308", "Región": "I", "Localidad": "LAS GOLONDRINAS", "Dependenci": "Provincial", "Oferta": "Inicial; Primaria; Secundaria; Especial Secundaria", "Nivel": "Domiciliaria - Hospitalaria", "Modalidad": "Común; Especial", "cod_area": "2944", "telefono": "4473127", "email": "escuela308@gmail.com", "sitioweb": null, "responsabl": "Martinez Nora", "resp_tel": "0294-473129", "resp_email": "escuela308@gmail.com", "departamen": "CUSHAMEN", "calle": "CAMINO DE LA CRUZ", "num_calle": "NULL", "cod_postal": "U9211" }, "geometry": { "type": "Point", "coordinates": [ -71.5322866, -42.0150071 ] } }
	
	]
};