var ed_artistica = {
	"type": "FeatureCollection",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },                                                                               
	"features": [
		{ "type": "Feature", "properties": { "fna": "MAESTRO CLYDWYN AP AERON JONESNº 805 - TRELEW", "fun": "Activo", "cueanexo": "260015501", "amg": "Urbano", "ges": "Estatal", "codJurid": "805", "Región": "IV", "Localidad": "TRELEW", "Dependenci": "Provincial", "Oferta": "Cursos y Talleres de Artística", "Nivel": "Artística", "Modalidad": "Común", "cod_area": "280", "telefono": "4427668", "email": "fav805trelew@gmail.com", "sitioweb": "http:  isfd805.chu.infd.edu.ar", "responsabl": "Sonia Alejandra Baliente", "resp_tel": "0280-427668", "resp_email": "direccion805@hotmail.com", "departamen": "RAWSON", "calle": "ROQUE GONZÁLEZ", "num_calle": null, "cod_postal": "U9100" }, "geometry": { "type": "Point", "coordinates": [ -65.2922905, -43.2466958 ] } },
		{ "type": "Feature", "properties": { "fna": "MAESTRO CLYDWYN AP AERON JONES Nº 805 - GAIMAN", "fun": "Activo", "cueanexo": "260015502", "amg": "Urbano", "ges": "Estatal", "codJurid": "805", "Región": "IV", "Localidad": "GAIMAN", "Dependenci": "Provincial", "Oferta": "Cursos y Talleres de Artística", "Nivel": "Artística", "Modalidad": "Común", "cod_area": "280", "telefono": "4491601", "email": "gaiman805@yahoo.com.ar", "sitioweb": "http:  isfd805.chu.infd.edu.ar", "responsabl": "Sonia Alejandra Baliente", "resp_tel": "0280-427668", "resp_email": "direccion805@hotmail.com", "departamen": "GAIMAN", "calle": "AVDA. EUGENIO TELLO", "num_calle": "384", "cod_postal": "U9105" }, "geometry": { "type": "Point", "coordinates": [ -65.4965501, -43.2905083 ] } },
		{ "type": "Feature", "properties": { "fna": "MAESTRO CLYDWYN AP AERON JONESNº 805 - PUERTO MADRYN", "fun": "Activo", "cueanexo": "260015504", "amg": "Urbano", "ges": "Estatal", "codJurid": "805", "Región": "II", "Localidad": "PUERTO MADRYN", "Dependenci": "Provincial", "Oferta": "Cursos y Talleres de Artística", "Nivel": "Artística", "Modalidad": "Común", "cod_area": "280", "telefono": "4451676", "email": "madryn805@yahoo.com.ar", "sitioweb": "http:  isfd805.chu.infd.edu.ar", "responsabl": "Sonia Alejandra Baliente", "resp_tel": "0280-427668", "resp_email": "direccion805@hotmail.com", "departamen": "BIEDMA", "calle": "AGUSTÍN PUJOL", "num_calle": "251", "cod_postal": "U9120" }, "geometry": { "type": "Point", "coordinates": [ -65.0408, -42.7601 ] } },
		{ "type": "Feature", "properties": { "fna": "MAESTRO CLYDWYN AP AERON JONESNº 805 - RAWSON", "fun": "Activo", "cueanexo": "260015505", "amg": "Urbano", "ges": "Estatal", "codJurid": "805", "Región": "IV", "Localidad": "RAWSON", "Dependenci": "Provincial", "Oferta": "Cursos y Talleres de Artística", "Nivel": "Artística", "Modalidad": "Común", "cod_area": "280", "telefono": "4485589", "email": "direccion805@hotmail.com", "sitioweb": "http:  isfd805.chu.infd.edu.ar", "responsabl": "Sonia Alejandra Baliente", "resp_tel": "0280-427668", "resp_email": "direccion805@hotmail.com", "departamen": "RAWSON", "calle": "LUIS GONZÁLEZ", "num_calle": null, "cod_postal": "U9103" }, "geometry": { "type": "Point", "coordinates": [ -65.0820662, -43.2887545 ] } },
		{ "type": "Feature", "properties": { "fna": "MAESTRO CLYDWYN AP AERON JONES N° 805 - 28 DE JULIO", "fun": "Activo", "cueanexo": "260015506", "amg": "Rural", "ges": "Estatal", "codJurid": "805", "Región": "IV", "Localidad": "28 DE JULIO", "Dependenci": "Provincial", "Oferta": "Cursos y Talleres de Artística", "Nivel": "Artística", "Modalidad": "Común", "cod_area": "280", "telefono": "4864784", "email": "esc28dejulio805@outlook.com", "sitioweb": "isfd805.chu.infd.edu.ar", "responsabl": "Sonia Alejandra Baliente", "resp_tel": "0280-427668", "resp_email": "direccion805@hotmail.com", "departamen": "GAIMAN", "calle": "CHACRA 338-RUTA 7", "num_calle": null, "cod_postal": "U9107" }, "geometry": { "type": "Point", "coordinates": [ -65.8392993, -43.389018 ] } },
		{ "type": "Feature", "properties": { "fna": "I.S.F.D. ARTÍSTICA Nº 814", "fun": "Activo", "cueanexo": "260067501", "amg": "Urbano", "ges": "Estatal", "codJurid": "814", "Región": "I", "Localidad": "EL HOYO", "Dependenci": "Provincial", "Oferta": "Cursos y Talleres de Artística", "Nivel": "Artística", "Modalidad": "Común", "cod_area": "294", "telefono": "4471571", "email": "814direccion@gmail.com 814elhoyo@gmail.com", "sitioweb": "www.isfda814.com.ar", "responsabl": "Pablo Esteban Acosta", "resp_tel": "2944376403", "resp_email": "814direccion@gmail.com", "departamen": "CUSHAMEN", "calle": "LOS DURAZNOS", "num_calle": null, "cod_postal": "U9211" }, "geometry": { "type": "Point", "coordinates": [ -71.4884813, -42.0860561 ] } }
		
	]
};