var supervicion_secundaria = {
	"type": "FeatureCollection",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },                                                                               
	"features": [
{ "type": "Feature", "properties": { "nombreSupe": "Las Golondrinas", "direccion": "Callejon de la Cruz", "Responsabl": "Prof. Silvia Iglesias – Prof. Carola Aragón", "Tel": "(02944) 4473079", "email": "stepregion1@gmail.com", "tipoSuperv": "Secundaria", "numReg": "I", "Nivel": "Secundario" }, "geometry": { "type": "Point", "coordinates": [ -71.5330157, -42.015728 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Puerto Madryn", "direccion": "Mitre y Rivadavia", "Responsabl": "Prof. Elsa Gladys Duarte – Prof. Miguel Leonardo Bagnato", "Tel": "(0280) 4450194", "email": "suptecpm@gmail.com", "tipoSuperv": "Secundaria", "numReg": "II", "Nivel": "Secundario" }, "geometry": { "type": "Point", "coordinates": [ -65.0303534, -42.7753373 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Esquel", "direccion": "Alvear 1160", "Responsabl": "Prof. Juan Domingo Martinez – Prof. Daniela Otero – Prof. Oscar Alfredo Lenarduzzi (Rural) – Prof. Gustavo Reguiló", "Tel": "(02945) 451415", "email": "secundariar3@gmail.com", "tipoSuperv": "Secundaria", "numReg": "III", "Nivel": "Secundario" }, "geometry": { "type": "Point", "coordinates": [ -71.3217703, -42.9122953 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Trelew", "direccion": "25 de Mayo 371", "Responsabl": "Prof. Tania Chicha – Prof. Mónica Albornoz – Prof. Patricia Ibarrola (Rural) – Prof. Claudia Ríos – Prof. Elida Pérez – Prof. Paola Vicente", "Tel": "(0280) 4427709", "email": "supervisionsec.reg.iv@gmail.com", "tipoSuperv": "Secundaria", "numReg": "IV", "Nivel": "Secundario" }, "geometry": { "type": "Point", "coordinates": [ -65.311456, -43.2530983 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Rawson", "direccion": "Av. 9 de Julio N°24", "Responsabl": "Prof. Raquel Inalaf", "Tel": "(0280) 4486483", "email": "stes.rawson@gmail.com", "tipoSuperv": "Secundaria", "numReg": "IV", "Nivel": "Secundario" }, "geometry": { "type": "Point", "coordinates": [ -65.1028456, -43.2980142 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Sarmiento", "direccion": "Av. Regimiento de Infantería Mecanizada 25 N° 32", "Responsabl": "Prof. Sandro Molina", "Tel": "(0297) 4892173", "email": "supervsecundario5@hotmail.com", "tipoSuperv": "Secundaria", "numReg": "V", "Nivel": "Secundario" }, "geometry": { "type": "Point", "coordinates": [ -69.0690925, -45.5939637 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Supervición Técinica General", "direccion": "Av. 9 de Julio N°24", "Responsabl": "Prof. Sonia Menéndez", "Tel": "(0280) 4482361\/44", "email": "suptecgralsec@gmail.com", "tipoSuperv": "Secundaria", "numReg": "IV", "Nivel": "Secundario" }, "geometry": { "type": "Point", "coordinates": [ -65.1028193, -43.2979916 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Comodoro Rivadavia", "direccion": null, "Responsabl": "Prof. Sonia Menéndez", "Tel": null, "email": "suptecgralsec@gmail.com", "tipoSuperv": "Secundaria", "numReg": "VI", "Nivel": "Secundario" }, "geometry": { "type": "Point", "coordinates": [ -67.478832, -45.8399387 ] } },
	]
};