var supervicion_primaria = {
	"type": "FeatureCollection",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },                                                                               
	"features": [
{ "type": "Feature", "properties": { "nombreSupe": "Trelew", "Responsabl": "Prof. Alicia Pavón", "email": "supseccreg4@gmail.com", "numReg": "IV", "Tel": "(0280) 4429630 \/ 4432763", "tipoSuperv": "Primaria", "direccion": "Hipólito Yrigoyen, esquina Martín Fierro (Escuela N° 85)", "Nivel": "Primario" }, "geometry": { "type": "Point", "coordinates": [ -65.296526, -43.2595902 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Puerto Madryn", "Responsabl": "Prof. Cecilia Rosales", "email": "supreg2@gmail.com", "numReg": "II", "Tel": "(0280) 4456960 \/4451428 \/ 4454615 \/ 154653176", "tipoSuperv": "Primaria", "direccion": "25 de Mayo y Rivadavia", "Nivel": "Primario" }, "geometry": { "type": "Point", "coordinates": [ -65.0304308, -42.7752683 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Esquel", "Responsabl": "Prof. Patricia Moreyra", "email": "supregion3@gmail.com", "numReg": "III", "Tel": "(02945) 455597 \/ 450569 \/ 450833", "tipoSuperv": "Primaria", "direccion": "Av. Alvear Nº 1160", "Nivel": "Primario" }, "geometry": { "type": "Point", "coordinates": [ -71.3217632, -42.9122646 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Sarmiento", "Responsabl": "Sara Antiñir", "email": "supregion5@gmail.com", "numReg": "V", "Tel": "(0297) 4893648 \/ 4893633 \/ 154525970", "tipoSuperv": "Primaria", "direccion": "Estrada Nº 750", "Nivel": "Primario" }, "geometry": { "type": "Point", "coordinates": [ -69.0748693, -45.5901204 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Comodoro Rivadavia", "Responsabl": "Prof. Alejandra Caamaño", "email": "supregion6@gmail.com", "numReg": "VI", "Tel": "(0297) 4557086", "tipoSuperv": "Primaria", "direccion": "Marcelino Reyes y José Fuchs – Bº Gral. Mosconi – Km 3", "Nivel": "Primario" }, "geometry": { "type": "Point", "coordinates": [ -67.4788233, -45.8399043 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Las Golondrinas", "Responsabl": "Prof. María Elisa Vazquez", "email": "supervisionregionuno@gmail.com", "numReg": "I", "Tel": "(02944) 471802 \/ 473065", "tipoSuperv": "Primaria", "direccion": "Calle de la Cruz", "Nivel": "Primario" }, "geometry": { "type": "Point", "coordinates": [ -71.5327875, -42.0151276 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Supervisión Técinica General", "Responsabl": "Prof. Lilia Edith Yañez", "email": null, "numReg": "IV", "Tel": null, "tipoSuperv": "Primaria", "direccion": "Av. 9 de Julio Nº 24", "Nivel": "Primario" }, "geometry": { "type": "Point", "coordinates": [ -65.1028704, -43.2980101 ] } },
	]
};