var supervicion_inicial = {
	"type": "FeatureCollection",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },                                                                               
	"features": [
{ "type": "Feature", "properties": { "nombreSupe": "Puerto Madryn", "direccion": "Mitre Nº 1066", "Responsabl": "Soledad Ciancio – Claudia Valenzuela – Marlene García", "Tel": "(0280) 4456625\/4454365", "email": "supervisioninicialmadryn@gmail.com", "tipoSuperv": "Inicial", "numReg": "II", "Nivel": "Inicial" }, "geometry": { "type": "Point", "coordinates": [ -65.0349344, -42.7704516 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Esquel", "direccion": "Av. Alvear 1066", "Responsabl": "Marta Toledo – Claudia García Esparza – Cielo Ferré", "Tel": "(02945) 451904", "email": "nivelinireg3@gmail.com", "tipoSuperv": "Inicial", "numReg": "III", "Nivel": "Inicial" }, "geometry": { "type": "Point", "coordinates": [ -71.3217955, -42.9122602 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Trelew", "direccion": "Maipú 510", "Responsabl": "Patricia Roque – Lina Dianda – Marina Méndez – Daniela Valda", "Tel": "(0280) 4429534", "email": "inicialcuarta@hotmail.com", "tipoSuperv": "Inicial", "numReg": "IV", "Nivel": "Inicial" }, "geometry": { "type": "Point", "coordinates": [ -65.3020456, -43.2623966 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Comodoro Rivadavia", "direccion": "Marcelino Reyes y José Fuichs", "Responsabl": "Prof. Rosa Velázquez – Prof. Patricia Mendoza – Prof. Asencio Nuria  – Prof. Claudia Larrea", "Tel": "(0297) 4557258", "email": "supervisioninicial@gmail.com", "tipoSuperv": "Inicial", "numReg": "VI", "Nivel": "Inicial" }, "geometry": { "type": "Point", "coordinates": [ -67.4788556, -45.8399418 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Supervisión Técnica General", "direccion": "Av. 9 de Julio Nº 24", "Responsabl": "Lic. Sandra Boubeé", "Tel": "(0280) 4482341", "email": null, "tipoSuperv": "Inicial", "numReg": "IV", "Nivel": "Inicial" }, "geometry": { "type": "Point", "coordinates": [ -65.1029126, -43.2979727 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Sarmiento", "direccion": "San Martín y Pellegrini", "Responsabl": "María Rosa Caroscio – Lucrecia Alonso", "Tel": "(0297) 4894416", "email": "supinicialsarmiento@hotmail.com", "tipoSuperv": "Inicial", "numReg": "V", "Nivel": "Inicial" }, "geometry": { "type": "Point", "coordinates": [ -69.0699373, -45.5919285 ] } },
{ "type": "Feature", "properties": { "nombreSupe": "Las Golondrinas", "direccion": "Callejón de la Cruz", "Responsabl": "Gabriela Verdejo – Mariela Parra", "Tel": "(02944) 473036", "email": "senir1@yahoo.com.ar", "tipoSuperv": "Inicial", "numReg": "I", "Nivel": "Inicial" }, "geometry": { "type": "Point", "coordinates": [ -71.5331076, -42.0153758 ] } },
	]
};